import type { Shoe } from "../types.js";

export const ADIDAS: Shoe[] = [
  // ── DAILY TRAINERS ───────────────────────────────────────────────────────────

  {
    id: "adidas-supernova-rise",
    brand: "adidas",
    model: "Supernova Rise",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 37, forefootStack: 27, drop: 10, weightGrams: 285, msrp: 130 },
        foam: "DREAMSTRIKE+ (Lightstrike Pro + EVA base)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["DREAMSTRIKE+ dual foam", "Lightstrike Pro top layer", "10mm drop"],
        useCases: ["daily-trainer", "long-run"],
        notes: "adidas' versatile daily trainer. DREAMSTRIKE+ blends Lightstrike Pro softness with firmer EVA base. Competitive price point.",
      },
      {
        version: "3",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 291, msrp: 140 },
        foam: "DREAMSTRIKE+ (upgraded PEBA blend, 20% softer/bouncier)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+3mm heel /+5mm forefoot vs Rise 2", "drop reduced 10mm → 8mm", "upgraded DREAMSTRIKE+ (20% softer/bouncier)", "Primeweave upper"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Road Trail Run 'No-compromises package at $140'. Significantly upgraded foam and stack vs Rise 2. Drop moved from 10mm to 8mm. Strong daily trainer value.",
      },
    ],
  },

  {
    id: "adidas-evo-sl",
    brand: "adidas",
    model: "Adizero EVO SL",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "1",
        year: 2025,
        spec: { heelStack: 41, forefootStack: 33, drop: 8, weightGrams: 238, msrp: 160 },
        foam: "DREAMSTRIKE+ (PEBA-blend supercritical)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["plateless PEBA-blend DREAMSTRIKE+", "highly responsive", "lightweight", "rocker geometry"],
        useCases: ["daily-trainer", "tempo", "long-run"],
        notes: "Run Testers 'Contender for best shoe of 2025'. Plateless PEBA-blend super trainer. Top-rated in its class. Slight stability concern for overpronators.",
      },
      {
        version: "2",
        year: 2026,
        spec: { heelStack: 42, forefootStack: 34, drop: 8, weightGrams: 235, msrp: 165 },
        foam: "DREAMSTRIKE+ (updated PEBA-blend)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+1mm stack", "3g lighter", "updated outsole", "ATR winterised variant available"],
        useCases: ["daily-trainer", "tempo", "long-run"],
        notes: "Updated EVO SL. Run Testers 'First Adidas shoe you should check out'. Marginal stack and weight improvement. Competes with Saucony Endorphin Azura and Brooks Ghost Max.",
      },
    ],
  },

  {
    id: "adidas-supernova-solution",
    brand: "adidas",
    model: "Supernova Solution",
    category: "stability",
    cushion: "moderate",
    variants: [
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 36, forefootStack: 28, drop: 8, weightGrams: 291, msrp: 130 },
        foam: "DREAMSTRIKE+",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["medial stability system", "DREAMSTRIKE+ foam", "8mm drop"],
        useCases: ["daily-trainer", "long-run"],
        notes: "adidas' stability daily trainer. DREAMSTRIKE+ foam with medial post. 8mm drop is lower than most stability competitors.",
      },
    ],
  },

  // ── PERFORMANCE / SUPER TRAINERS ─────────────────────────────────────────────

  {
    id: "adidas-boston",
    brand: "adidas",
    model: "Adizero Boston",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "12",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 30, drop: 9, weightGrams: 253, msrp: 180 },
        foam: "Lightstrike Pro + Lightstrike EVA",
        plate: { present: true, material: "fiberglass", description: "ENERGYRODS 2.0 (fiberglass rods)" },
        surfaces: ["road"],
        rocker: true,
        features: ["ENERGYRODS 2.0 fiberglass rods", "Lightstrike Pro top + Lightstrike EVA base", "9mm drop", "marathon training companion"],
        useCases: ["tempo", "long-run", "daily-trainer"],
        notes: "Premium plated training shoe with fiberglass ENERGYRODS instead of a single carbon plate. RTINGS: 'more premium super trainer with fiberglass stability'. More stable than EVO SL.",
      },
      {
        version: "13",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 31, drop: 9, weightGrams: 250, msrp: 185 },
        foam: "Lightstrike Pro + Lightstrike EVA",
        plate: { present: true, material: "fiberglass", description: "ENERGYRODS 2.0 (updated fiberglass)" },
        surfaces: ["road"],
        rocker: true,
        features: ["updated ENERGYRODS 2.0", "+1mm stack", "updated upper", "3g lighter"],
        useCases: ["tempo", "long-run", "daily-trainer"],
        notes: "RunRepeat best overall adidas training shoe 2026. Excellent for marathon training — stable, propulsive, and durable.",
      },
    ],
  },

  {
    id: "adidas-takumi-sen",
    brand: "adidas",
    model: "Adizero Takumi Sen",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "10",
        year: 2024,
        spec: { heelStack: 38, forefootStack: 30, drop: 8, weightGrams: 183, msrp: 220 },
        foam: "Lightstrike Pro",
        plate: { present: true, material: "carbon", description: "ENERGYRODS 2.0 carbon rods" },
        surfaces: ["road", "track"],
        rocker: true,
        features: ["ultra-lightweight", "minimal upper", "carbon ENERGYRODS", "track/5K optimized"],
        useCases: ["race", "track"],
        notes: "adidas' most stripped-back racer. For 5K and 10K specialists or track work. Highly responsive but less durable than Boston.",
      },
      {
        version: "11",
        year: 2025,
        spec: { heelStack: 38, forefootStack: 30, drop: 8, weightGrams: 179, msrp: 230 },
        foam: "Lightstrike Pro",
        plate: { present: true, material: "carbon", description: "ENERGYRODS 2.0 carbon" },
        surfaces: ["road", "track"],
        rocker: true,
        features: ["4g lighter than Takumi Sen 10", "updated minimal upper"],
        useCases: ["race", "track"],
        notes: "RunRepeat 'Best for 5K/10K adidas 2026'. Slightly lighter. Same ultra-responsive character.",
      },
    ],
  },

  // ── RACE ─────────────────────────────────────────────────────────────────────

  {
    id: "adidas-adios-pro",
    brand: "adidas",
    model: "Adizero Adios Pro",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "3",
        year: 2023,
        spec: { heelStack: 39, forefootStack: 31, drop: 8, weightGrams: 201, msrp: 250 },
        foam: "Lightstrike Pro (PEBA)",
        plate: { present: true, material: "carbon", description: "EnergyRods 2.0 (5 carbon rods)" },
        surfaces: ["road"],
        rocker: true,
        features: ["EnergyRods 2.0 (5 carbon+glass fiber rods)", "Lightstrike Pro PEBA", "ultra-light"],
        useCases: ["race", "tempo"],
        notes: "adidas flagship marathon racer. Multi-rod EnergyRods instead of a single plate — unique feel. Competes with Vaporfly and MetaSpeed Sky.",
      },
      {
        version: "4",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 196, msrp: 260 },
        foam: "Lightstrike Pro (updated PEBA)",
        plate: { present: true, material: "carbon", description: "EnergyRods 2.0 (updated geometry)" },
        surfaces: ["road"],
        rocker: true,
        features: ["updated EnergyRods geometry", "5g lighter than Pro 3", "improved heel", "+1mm stack"],
        useCases: ["race", "tempo"],
        notes: "RunRepeat 'Best for Race adidas 2026'. 196g. Top-tier marathon racer. Lightest Adios Pro yet.",
      },
    ],
  },

  {
    id: "adidas-prime-x3",
    brand: "adidas",
    model: "Adizero Prime X",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "3 STRUNG",
        year: 2025,
        spec: { heelStack: 50, forefootStack: 42, drop: 8, weightGrams: 232, msrp: 500 },
        foam: "Lightstrike Pro (max stack)",
        plate: { present: true, material: "carbon", description: "EnergyRods extreme geometry" },
        surfaces: ["road"],
        rocker: true,
        features: ["50mm heel stack (extreme)", "STRUNG upper technology", "limited edition", "8mm drop"],
        useCases: ["race"],
        notes: "Extreme high-stack racing experiment. 50mm heel stack. Limited edition — for collectors and boundary-pushers. Not for daily training.",
      },
    ],
  },
];
