import type { Shoe } from "../types.js";

export const ASICS: Shoe[] = [
  // ── STABILITY ───────────────────────────────────────────────────────────────

  {
    id: "asics-gt-2000",
    brand: "ASICS",
    model: "GT-2000",
    category: "stability",
    cushion: "moderate",
    variants: [
      {
        version: "12",
        year: 2023,
        spec: { heelStack: 31, forefootStack: 21, drop: 10, weightGrams: 267, msrp: 130 },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["LITETRUSS medial support", "3D Space Construction midsole", "10mm drop"],
        useCases: ["daily-trainer", "tempo", "long-run"],
        notes: "Lightweight stability. LITETRUSS provides mild pronation control without intrusive medial post. 'Stability-that-never-gets-in-the-way.'",
      },
      {
        version: "13",
        year: 2024,
        spec: { heelStack: 31, forefootStack: 21, drop: 10, weightGrams: 267, msrp: 130 },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["updated upper (marginally firmer mesh)", "same midsole geometry as v12", "improved heel collar"],
        useCases: ["daily-trainer", "tempo", "long-run"],
        notes: "Very close to GT-2000 12 in ride. Upper slightly less soft. Same praised mild stability. Excellent for moderate overpronators wanting a light trainer.",
      },
      {
        version: "14",
        year: 2025,
        spec: { heelStack: 36.5, forefootStack: 28.5, drop: 10, weightGrams: 300, msrp: 135 },
        foam: "FF BLAST PLUS ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["significantly higher stack vs v13 (+5.5mm heel / +7.5mm forefoot)", "LITETRUSS", "heavier than v12/13"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Major architecture change from v13. Stack grew considerably and weight jumped to 300g. Less nimble than v12/13 but more cushioned for high mileage. Runner's World 'Best Value' 2026.",
      },
    ],
  },

  {
    id: "asics-kayano",
    brand: "ASICS",
    model: "GEL-Kayano",
    category: "stability",
    cushion: "max",
    variants: [
      {
        version: "30",
        year: 2023,
        spec: { heelStack: 33, forefootStack: 23, drop: 10, weightGrams: 310, msrp: 160 },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["4D Guidance System", "GEL heel+forefoot", "LITETRUSS", "wider base"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Flagship ASICS stability shoe. Maximum cushion with firm pronation control. Best for moderate-to-severe overpronators needing high protection.",
      },
      {
        version: "31",
        year: 2024,
        spec: { heelStack: 34, forefootStack: 24, drop: 10, weightGrams: 308, msrp: 165 },
        foam: "FF BLAST HYPER",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["FF BLAST HYPER (more responsive than ECO)", "4D Guidance System", "GEL technology", "2g lighter"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "FF BLAST HYPER adds energy return vs ECO in Kayano 30. One of the best stability max-cushion shoes. Best for overpronators wanting comfort over many miles.",
      },
      {
        version: "32",
        year: 2025,
        spec: { heelStack: 35, forefootStack: 25, drop: 10, weightGrams: 305, msrp: 170 },
        foam: "FF BLAST HYPER",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["updated 4D Guidance System", "+1mm stack", "improved GEL zones", "updated upper"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Runner's World 'Best for Stability' 2026. Incremental stack increase. Best stability max-cushion trainer in the ASICS line.",
      },
    ],
  },

  // ── NEUTRAL MAX CUSHION ──────────────────────────────────────────────────────

  {
    id: "asics-nimbus",
    brand: "ASICS",
    model: "GEL-Nimbus",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "25",
        year: 2023,
        spec: { heelStack: 40, forefootStack: 30, drop: 10, weightGrams: 309, msrp: 160 },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["GEL heel + forefoot", "3D Space Construction", "knit upper", "10mm drop"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "ASICS max-cushion neutral flagship. 40mm heel stack with 10mm drop. Well-suited for high-mileage neutral runners on hard surfaces.",
      },
      {
        version: "26",
        year: 2024,
        spec: { heelStack: 40, forefootStack: 30, drop: 10, weightGrams: 306, msrp: 165 },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["improved breathability upper", "3g lighter than Nimbus 25", "same GEL + FF stack"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Incremental refinement. Marginally lighter with improved airflow. Top tier max-cushion neutral trainer.",
      },
      {
        version: "27",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 30, drop: 10, weightGrams: 303, msrp: 165, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 303, refSize: "men's US 9" },
          womens: { weightGrams: 258, refSize: "women's US 8" },  // ~9.1oz
        },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["updated upper construction", "improved lockdown", "same midsole stack"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Runner's World 'Best Cushioning' 2026 ASICS pick. Consistent and reliable max-cushion neutral. Women's: ~9.1oz/258g.",
      },
      {
        version: "28",
        year: 2026,
        spec: { heelStack: 41, forefootStack: 31, drop: 10, weightGrams: 300, msrp: 170 },
        foam: "FF BLAST+ ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["+1mm stack vs Nimbus 27", "updated mesh", "improved heel support"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "2026 update. Marginal stack increase. Maintains the Nimbus identity as ASICS' top neutral max-cushion trainer.",
      },
    ],
  },

  // ── NEUTRAL MODERATE ─────────────────────────────────────────────────────────

  {
    id: "asics-cumulus",
    brand: "ASICS",
    model: "GEL-Cumulus",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "25",
        year: 2023,
        spec: { heelStack: 35, forefootStack: 25, drop: 10, weightGrams: 298, msrp: 130 },
        foam: "FF BLAST PLUS ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["FluidRide outsole", "engineered mesh", "GEL heel insert", "10mm drop"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "ASICS balanced/moderate-cushion neutral flagship. Sits below the Nimbus. Good for beginner-to-intermediate runners wanting reliable comfort.",
      },
      {
        version: "26",
        year: 2024,
        spec: { heelStack: 35, forefootStack: 25, drop: 10, weightGrams: 295, msrp: 130 },
        foam: "FF BLAST PLUS ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["updated upper", "slightly lighter", "improved FluidRide outsole"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Refinement of Cumulus 25. Reliable all-rounder. 10mm drop and approachable cushion. Runner's World 'Best Daily Trainer' ASICS 2026.",
      },
      {
        version: "27",
        year: 2025,
        spec: { heelStack: 36, forefootStack: 26, drop: 10, weightGrams: 292, msrp: 135 },
        foam: "FF BLAST PLUS ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["+1mm stack vs Cumulus 26", "updated geometry", "slight rocker profile"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Cumulus 27 adds a touch more stack and a slight rocker. More progressive than Cumulus 26 while keeping the accessible character.",
      },
    ],
  },

  {
    id: "asics-novablast",
    brand: "ASICS",
    model: "Novablast",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "4",
        year: 2024,
        spec: { heelStack: 37, forefootStack: 29, drop: 8, weightGrams: 282, msrp: 130 },
        foam: "FF BLAST PLUS ECO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["aggressive heel bevel", "TrailSet outsole", "8mm drop", "stability elements added vs Novablast 3"],
        useCases: ["daily-trainer", "tempo"],
        notes: "Reduced extreme bounciness of Novablast 3. Added stability. 8mm drop (lower than most ASICS). Fun geometry with efficient transitions.",
      },
      {
        version: "5",
        year: 2025,
        spec: { heelStack: 38, forefootStack: 30, drop: 8, weightGrams: 278, msrp: 135 },
        foam: "FF BLAST PLUS (lower density, softer/bouncier than ECO)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["lower-density softer/bouncier foam vs Novablast 4", "+1mm stack", "4g lighter", "8mm drop maintained"],
        useCases: ["daily-trainer", "tempo"],
        notes: "Runner's World 'Best Overall' ASICS 2026. Softer and bouncier foam gives pillowy feel + spring energy return — 'holy grail combo.' Best fun trainer in the ASICS lineup.",
      },
    ],
  },

  // ── SUPER TRAINERS / PERFORMANCE ─────────────────────────────────────────────

  {
    id: "asics-megablast",
    brand: "ASICS",
    model: "MEGABLAST",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "1",
        year: 2025,
        spec: { heelStack: 45, forefootStack: 36, drop: 9, weightGrams: 230, msrp: 180 },
        foam: "FF BLAST MAX (supercritical)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["high stack unplated super trainer", "supercritical foam", "9mm drop", "lively rebound"],
        useCases: ["daily-trainer", "long-run", "tempo"],
        notes: "RTINGS #1 ASICS pick 2026 — 'rare do-it-all mix of max cushioning, low weight, and lively rebound in an unplated package.' 229.9g per RTINGS testing.",
      },
    ],
  },

  {
    id: "asics-superblast",
    brand: "ASICS",
    model: "SUPERBLAST",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 45, forefootStack: 35, drop: 10, weightGrams: 218, msrp: 200 },
        foam: "FF BLAST TURBO",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["no plate — pure foam speed shoe", "very light for stack", "rocker geometry", "marathon training use"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "Unplated high-stack performance trainer. Very fast without the carbon plate. Used by elite runners for easy/moderate marathon training.",
      },
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 46, forefootStack: 36, drop: 10, weightGrams: 215, msrp: 210 },
        foam: "FF BLAST TURBO (updated)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+1mm stack vs SUPERBLAST 2", "3g lighter", "updated rocker geometry"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "Lighter and slightly more stack. Same unplated philosophy. RTINGS listed in top ASICS picks. Excellent if you want super-shoe performance without a plate.",
      },
    ],
  },

  {
    id: "asics-magic-speed",
    brand: "ASICS",
    model: "Magic Speed",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "4",
        year: 2024,
        spec: { heelStack: 38, forefootStack: 30, drop: 8, weightGrams: 234, msrp: 160 },
        foam: "FF BLAST TURBO",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["full-length carbon plate", "FF BLAST TURBO foam", "daily training companion to MetaSpeed"],
        useCases: ["tempo", "long-run", "daily-trainer"],
        notes: "Plated daily trainer companion to the MetaSpeed Sky+ racer. More durable than the race shoe. For marathon-pace workouts.",
      },
    ],
  },

  {
    id: "asics-metaspeed-sky",
    brand: "ASICS",
    model: "MetaSpeed Sky",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "Paris",
        year: 2024,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 186, msrp: 260 },
        foam: "FF BLAST TURBO+",
        plate: { present: true, material: "carbon", description: "curved full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["FF BLAST TURBO+ highest-energy ASICS foam", "carbon plate", "Paris Olympics edition geometry", "ultra-light"],
        useCases: ["race", "tempo"],
        notes: "ASICS' flagship marathon racer. Optimized for stride-length runners (vs MetaSpeed Edge for cadence). Highly competitive with Vaporfly and Adios Pro.",
      },
    ],
  },
];
