import type { Shoe } from "../types.js";

export const BROOKS: Shoe[] = [
  // ── DAILY NEUTRAL ────────────────────────────────────────────────────────────

  {
    id: "brooks-ghost",
    brand: "Brooks",
    model: "Ghost",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "15",
        year: 2023,
        spec: { heelStack: 36, forefootStack: 24, drop: 12, weightGrams: 283, msrp: 130 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["DNA Loft v3 foam", "12mm traditional drop", "segmented crash pad"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Classic workhorse. High 12mm drop suits heel strikers and Achilles-sensitive runners. DNA Loft v3 is soft but not plush.",
      },
      {
        version: "16",
        year: 2024,
        spec: { heelStack: 36, forefootStack: 24, drop: 12, weightGrams: 283, msrp: 140 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["refined upper", "same midsole geometry as Ghost 15", "improved outsole coverage"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Incremental update to Ghost 15. Same midsole. Consistently rated one of the best neutral daily trainers for heel strikers.",
      },
      {
        version: "17",
        year: 2025,
        spec: { heelStack: 36, forefootStack: 24, drop: 12, weightGrams: 278, msrp: 140, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 278, refSize: "men's US 9" },
          womens: { weightGrams: 258, refSize: "women's US 8" },  // ~9.1oz
        },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["5g lighter than Ghost 16", "updated mesh upper", "slightly wider toe box"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "#1 overall neutral daily trainer 2025 per Switchback Travel. Best Ghost yet. 12mm drop is its most distinctive feature. Women's: ~9.1oz/258g.",
      },
    ],
  },

  {
    id: "brooks-ghost-max",
    brand: "Brooks",
    model: "Ghost Max",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 295, msrp: 165 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["max-stack Ghost", "6mm drop (vs 12mm on Ghost)", "rocker geometry", "wide platform"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Max-cushion Ghost with 6mm drop instead of 12mm. Rocker geometry and wide base. #1 walking shoe 2026 per Mountain Journey Journal.",
      },
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 292, msrp: 165 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        widths: ["B", "D", "2E"],
        features: ["updated upper", "3g lighter", "rocker geometry maintained"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Slightly lighter Ghost Max 2. Excellent for high mileage, walking, or recovery. 6mm drop differentiates it from standard Ghost.",
      },
      {
        version: "4",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 289, msrp: 165 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["same midsole geometry", "updated breathable upper", "improved heel collar"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "2026 update. Keeps the winning 6mm drop + rocker + 40mm stack formula with minor upper improvements.",
      },
    ],
  },

  {
    id: "brooks-glycerin",
    brand: "Brooks",
    model: "Glycerin",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "21",
        year: 2024,
        spec: { heelStack: 38, forefootStack: 26, drop: 12, weightGrams: 295, msrp: 165 },
        foam: "DNA Loft v3 + DNA Glide",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["dual-foam midsole", "nitrogen-infused DNA Glide", "12mm traditional drop", "wide toe box"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Brooks' max-cushion flagship with traditional 12mm drop. DNA Glide adds energy return. Competes with HOKA Bondi 9 and ASICS Nimbus.",
      },
      {
        version: "22",
        year: 2025,
        spec: { heelStack: 38, forefootStack: 28, drop: 10, weightGrams: 292, msrp: 165 },
        foam: "DNA Tuned (dual-density)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["DNA Tuned dual-density (firmer forefoot in softer shell)", "drop reduced from 12mm to 10mm", "forefoot rocker", "more responsive than Glycerin 21"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Significant update: DNA Tuned dual-density foam replaces Loft v3+Glide, and drop drops from 12mm to 10mm. More responsive than Glycerin 21.",
      },
    ],
  },

  {
    id: "brooks-glycerin-gts",
    brand: "Brooks",
    model: "Glycerin GTS",
    category: "stability",
    cushion: "max",
    variants: [
      {
        version: "22",
        year: 2025,
        spec: { heelStack: 38, forefootStack: 28, drop: 10, weightGrams: 298, msrp: 175 },
        foam: "DNA Tuned (dual-density)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["GuideRails stability system", "DNA Tuned dual-density foam", "10mm drop", "max cushion with stability"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Stability version of Glycerin 22. Combines GuideRails knee guidance with the plush DNA Tuned midsole. For overpronators wanting max cushion.",
      },
    ],
  },

  // ── STABILITY ───────────────────────────────────────────────────────────────

  {
    id: "brooks-adrenaline-gts",
    brand: "Brooks",
    model: "Adrenaline GTS",
    category: "stability",
    cushion: "moderate",
    variants: [
      {
        version: "23",
        year: 2023,
        spec: { heelStack: 35, forefootStack: 23, drop: 12, weightGrams: 289, msrp: 140 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["GuideRails holistic support", "12mm drop", "no medial post"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "GuideRails guides the knee rather than correcting the foot. Less intrusive than traditional medial posts. Classic 12mm drop.",
      },
      {
        version: "24",
        year: 2024,
        spec: { heelStack: 35, forefootStack: 23, drop: 12, weightGrams: 286, msrp: 140 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["GuideRails", "updated upper with better lockdown", "wider base"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Lighter than v23. Competes directly with ASICS GT-2000 13. GuideRails particularly good for runners with excess knee excursion.",
      },
      {
        version: "25",
        year: 2025,
        spec: { heelStack: 36, forefootStack: 26, drop: 10, weightGrams: 284, msrp: 140 },
        foam: "DNA v3",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E"],
        features: ["drop reduced 12mm → 10mm", "softer than GTS 24", "GuideRails updated", "+1mm stack"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Major update: softer DNA v3 foam and drop reduced from 12mm to 10mm. Aligns with modern shoe trends. Considerably more cushioned feel than GTS 24.",
      },
    ],
  },

  {
    id: "brooks-launch",
    brand: "Brooks",
    model: "Launch",
    category: "neutral",
    cushion: "low",
    variants: [
      {
        version: "10",
        year: 2024,
        spec: { heelStack: 28, forefootStack: 16, drop: 12, weightGrams: 248, msrp: 100 },
        foam: "BioMoGo DNA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["lightweight", "12mm drop", "BioMoGo DNA foam", "budget price"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "Budget tempo trainer. Firm and light. Good for faster runners who want a no-frills training shoe or a budget race option.",
      },
    ],
  },

  // ── SPEED / PERFORMANCE ──────────────────────────────────────────────────────

  {
    id: "brooks-hyperion-max",
    brand: "Brooks",
    model: "Hyperion Max",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 242, msrp: 200 },
        foam: "DNA Gold (PEBA)",
        plate: { present: true, material: "nylon", description: "Speedvault nylon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["DNA Gold 100% PEBA foam", "Speedvault nylon plate", "8mm drop", "fast daily trainer"],
        useCases: ["tempo", "long-run", "daily-trainer"],
        notes: "Plated marathon training shoe. DNA Gold (PEBA) + nylon plate delivers lively ride for marathon-pace workouts. Brooks' step below the Hyperion Elite race shoe.",
      },
    ],
  },

  {
    id: "brooks-hyperion-elite",
    brand: "Brooks",
    model: "Hyperion Elite",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "5",
        year: 2025,
        spec: { heelStack: 39, forefootStack: 31, drop: 8, weightGrams: 196, msrp: 250 },
        foam: "DNA Gold (PEBA)",
        plate: { present: true, material: "carbon", description: "Speedvault+ carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["DNA Gold PEBA foam", "Speedvault+ carbon plate", "RapidRoll Rocker", "lightweight"],
        useCases: ["race", "tempo"],
        notes: "Brooks' flagship carbon marathon racer. DNA Gold PEBA foam + Speedvault+ carbon = true super-shoe performance. Run Testers top-rated carbon shoe for stable runners.",
      },
      {
        version: "6",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 193, msrp: 280 },
        foam: "DNA Gold (PEBA)",
        plate: { present: true, material: "carbon", description: "Speedvault+ carbon (adjusted angle)" },
        surfaces: ["road"],
        rocker: true,
        features: ["Speedvault+ carbon at more aggressive angle", "RapidRoll Rocker updated", "TPU pressed upper", "1mm more stack vs HE5"],
        useCases: ["race", "tempo"],
        notes: "2026 flagship racer. More aggressive Speedvault+ plate angle for earlier propulsion. TPU upper provides structure and stretch. 3g lighter than HE5.",
      },
    ],
  },

  // ── TRAIL ────────────────────────────────────────────────────────────────────

  {
    id: "brooks-cascadia",
    brand: "Brooks",
    model: "Cascadia",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "18",
        year: 2024,
        spec: { heelStack: 32, forefootStack: 22, drop: 10, weightGrams: 312, msrp: 140 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: false,
        features: ["TrailTack rubber outsole", "rock plate", "protective toe bumper", "10mm drop"],
        useCases: ["trail"],
        notes: "Long-standing trail workhorse. TrailTack outsole grips both wet and dry terrain. Rock plate protects from sharp terrain.",
      },
      {
        version: "19",
        year: 2025,
        spec: { heelStack: 32, forefootStack: 22, drop: 10, weightGrams: 308, msrp: 145 },
        foam: "DNA Loft v3",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: false,
        features: ["updated TrailTack outsole", "improved drainage ports", "slightly lighter"],
        useCases: ["trail"],
        notes: "Best Brooks trail shoe per SoleReview 2025. Incremental improvements to the proven Cascadia formula.",
      },
    ],
  },
];
