import type { Shoe } from "../types.js";

export const HOKA: Shoe[] = [
  // ── DAILY NEUTRAL ────────────────────────────────────────────────────────────

  {
    id: "hoka-clifton",
    brand: "HOKA",
    model: "Clifton",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "8",
        year: 2022,
        spec: { heelStack: 32, forefootStack: 27, drop: 5, weightGrams: 255, msrp: 140 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["5mm low drop", "early meta-rocker geometry", "lightweight for stack"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Beloved lightweight daily trainer. 5mm drop promoted midfoot-forward gait. CMEVA is durable but less resilient than premium foams.",
      },
      {
        version: "9",
        year: 2024,
        spec: { heelStack: 41, forefootStack: 33, drop: 8, weightGrams: 251, msrp: 145 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["major redesign: +9mm heel stack vs Clifton 8", "drop increased 5mm → 8mm", "4g lighter"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Significant redesign over Clifton 8. More cushion and more drop. Some purists preferred Clifton 8's lower drop feel.",
      },
      {
        version: "10",
        year: 2025,
        spec: { heelStack: 51, forefootStack: 43, drop: 8, weightGrams: 249, msrp: 145 },
        foam: "CMEVA (updated)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+10mm heel stack vs Clifton 9", "2g lighter", "smooth from-first-wear feel", "improved outsole"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Marathon Sports 'Best Daily Training HOKA 2026'. 51mm heel stack is among the highest for a daily trainer. Easy from first wear.",
      },
    ],
  },

  {
    id: "hoka-bondi",
    brand: "HOKA",
    model: "Bondi",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "8",
        year: 2023,
        spec: { heelStack: 41, forefootStack: 36, drop: 4, weightGrams: 298, msrp: 165 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["4mm ultra-low drop", "widest platform in HOKA line", "very high stack for year", "extended heel"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "HOKA's max-cushion flagship. 4mm drop is very low for a max-cushion shoe. Cult favourite for ultra runners and those on hard surfaces.",
      },
      {
        version: "9",
        year: 2024,
        spec: { heelStack: 43, forefootStack: 38, drop: 4, weightGrams: 298, msrp: 175, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 298, refSize: "men's US 9" },
          womens: { weightGrams: 264, refSize: "women's US 8" },  // 9.30oz per HOKA official
        },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+2mm heel/+2mm forefoot vs Bondi 8", "same 4mm low drop", "wider platform", "updated upper"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "More stack, same ultra-low 4mm drop. One of the highest-stack daily trainers at 43mm. Mountain Journey Journal 'Best Walking Shoe 2026'. Women's: 9.30oz/264g per HOKA official.",
      },
    ],
  },

  {
    id: "hoka-rincon",
    brand: "HOKA",
    model: "Rincon",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "3",
        year: 2022,
        spec: { heelStack: 32, forefootStack: 26, drop: 5, weightGrams: 222, msrp: 125 },
        foam: "CMEVA lightweight",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["extremely lightweight", "5mm drop", "breathable engineered mesh", "minimal overlays"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "HOKA's lightest road shoe. Fast and fun for easy-to-moderate efforts. Less durable than Clifton due to thinner construction.",
      },
      {
        version: "4",
        year: 2024,
        spec: { heelStack: 34, forefootStack: 28, drop: 5, weightGrams: 218, msrp: 130 },
        foam: "CMEVA lightweight",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+2mm stack vs Rincon 3", "4g lighter", "updated outsole", "revised upper fit"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "Lighter than Rincon 3 with slightly more stack. HOKA's workhorse for runners wanting a light, affordable daily trainer.",
      },
    ],
  },

  // ── TEMPO / SPEED ─────────────────────────────────────────────────────────────

  {
    id: "hoka-mach",
    brand: "HOKA",
    model: "Mach",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "6",
        year: 2024,
        spec: { heelStack: 36, forefootStack: 29, drop: 7, weightGrams: 228, msrp: 145 },
        foam: "supercritical CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["supercritical CMEVA (lighter, more resilient)", "7mm drop", "meta-rocker geometry"],
        useCases: ["tempo", "daily-trainer"],
        notes: "HOKA's lightweight tempo trainer. Supercritical CMEVA delivers firm, responsive ride. Good for workouts and moderate-pace long runs where Clifton is too plush.",
      },
      {
        version: "7",
        year: 2025,
        spec: { heelStack: 37, forefootStack: 30, drop: 5, weightGrams: 225, msrp: 145, refSize: "men's UK 9" },
        genderVariants: {
          mens:   { weightGrams: 225, refSize: "men's UK 9 / US 9.5" },
          womens: { weightGrams: 198, refSize: "women's US 8" },
        },
        foam: "supercritical CMEVA (updated)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["drop reduced 7mm → 5mm", "3g lighter than Mach 6", "+1mm stack", "updated outsole tread"],
        useCases: ["tempo", "daily-trainer"],
        notes: "Run Testers 'Favourite HOKA Daily Trainer 2026'. Drop reduced to 5mm, 3g lighter. More versatile than Clifton 10, cheaper than Mach X3. Best all-round HOKA for runners.",
      },
    ],
  },

  {
    id: "hoka-mach-x",
    brand: "HOKA",
    model: "Mach X",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 40, forefootStack: 33, drop: 5, weightGrams: 249, msrp: 180 },
        foam: "supercritical CMEVA",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["full-length carbon plate", "supercritical CMEVA", "5mm drop", "fast trainer/racer hybrid"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "Plated super trainer. Carbon plate + supercritical CMEVA = springy propulsive ride. More stable than Rocket X for everyday fast training.",
      },
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 41, forefootStack: 34, drop: 5, weightGrams: 245, msrp: 185 },
        foam: "supercritical CMEVA (updated)",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["+1mm stack", "4g lighter", "updated carbon plate geometry", "improved upper"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "Run Testers: step up from Rocket X3 for those who find full race shoes too unstable. Great for marathon training and half-marathon racing.",
      },
    ],
  },

  // ── RACE ─────────────────────────────────────────────────────────────────────

  {
    id: "hoka-rocket-x",
    brand: "HOKA",
    model: "Rocket X",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2023,
        spec: { heelStack: 39, forefootStack: 33, drop: 5, weightGrams: 211, msrp: 225 },
        foam: "PEBA + CMEVA",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["PEBA foam top layer", "full-length carbon", "5mm low drop", "HOKA's fastest shoe"],
        useCases: ["race", "tempo"],
        notes: "HOKA's flagship marathon racer. 5mm drop differentiates it from other carbon shoes. PEBA layer delivers excellent energy return.",
      },
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 34, drop: 5, weightGrams: 206, msrp: 235 },
        foam: "PEBA + supercritical CMEVA",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["updated PEBA foam", "+1mm stack", "5g lighter", "revised plate geometry"],
        useCases: ["race", "tempo"],
        notes: "Marathon Sports 'Best Racing HOKA 2026'. Lightest Rocket X yet. 5mm drop and PEBA foam make it distinctive among carbon racers.",
      },
    ],
  },

  // ── STABILITY ─────────────────────────────────────────────────────────────────

  {
    id: "hoka-arahi",
    brand: "HOKA",
    model: "Arahi",
    category: "stability",
    cushion: "high",
    variants: [
      {
        version: "7",
        year: 2023,
        spec: { heelStack: 36, forefootStack: 31, drop: 5, weightGrams: 262, msrp: 140 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["J-Frame stability (firmer medial foam)", "5mm drop", "meta-rocker"],
        useCases: ["daily-trainer", "long-run"],
        notes: "HOKA's moderate stability option. J-Frame is a firmer foam structure wrapping the medial side — less intrusive than traditional medial posts. Low 5mm drop.",
      },
      {
        version: "8",
        year: 2025,
        spec: { heelStack: 37, forefootStack: 32, drop: 5, weightGrams: 258, msrp: 140 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["J-Frame stability", "+1mm stack", "updated upper", "5mm drop maintained"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Marathon Sports 'Best Stability HOKA 2026'. J-Frame provides gentle guidance. 5mm drop is unusually low for a stability shoe.",
      },
    ],
  },

  {
    id: "hoka-gaviota",
    brand: "HOKA",
    model: "Gaviota",
    category: "stability",
    cushion: "max",
    variants: [
      {
        version: "5",
        year: 2024,
        spec: { heelStack: 42, forefootStack: 37, drop: 5, weightGrams: 298, msrp: 175 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["J-Frame stability system", "5mm low drop", "widest base in HOKA lineup", "max cushion + stability"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "HOKA's max-cushion stability option. J-Frame provides gentle medial support without aggressive post. 5mm drop unusual for stability max-cushion category.",
      },
      {
        version: "6",
        year: 2025,
        spec: { heelStack: 43, forefootStack: 38, drop: 5, weightGrams: 295, msrp: 175 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+1mm stack vs Gaviota 5", "updated J-Frame geometry", "RTINGS top stability pick"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "RTINGS listed as top stability HOKA. Best for overpronators who want max cushion with gentle guidance and low drop.",
      },
    ],
  },

  // ── TRAIL ─────────────────────────────────────────────────────────────────────

  {
    id: "hoka-speedgoat",
    brand: "HOKA",
    model: "Speedgoat",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "6",
        year: 2023,
        spec: { heelStack: 32, forefootStack: 25, drop: 4, weightGrams: 298, msrp: 155 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: true,
        features: ["Vibram Megagrip outsole", "4mm drop", "oversized lugs for aggressive terrain"],
        useCases: ["trail"],
        notes: "HOKA's flagship trail shoe. Vibram Megagrip outsole with aggressive multi-directional lugs. 4mm drop good for technical terrain.",
      },
      {
        version: "7",
        year: 2025,
        spec: { heelStack: 33, forefootStack: 26, drop: 4, weightGrams: 293, msrp: 165 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: true,
        features: ["Vibram Megagrip", "updated lug pattern", "improved drainage", "5g lighter"],
        useCases: ["trail"],
        notes: "Marathon Sports 'Best Trail HOKA 2026'. Lighter and improved drainage over Speedgoat 6.",
      },
    ],
  },

  {
    id: "hoka-challenger",
    brand: "HOKA",
    model: "Challenger ATR",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "7",
        year: 2023,
        spec: { heelStack: 30, forefootStack: 26, drop: 4, weightGrams: 255, msrp: 130 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["trail", "road"],
        rocker: true,
        features: ["versatile road-trail", "4mm drop", "multi-terrain outsole", "lightweight"],
        useCases: ["trail", "daily-trainer"],
        notes: "Best for mixed surfaces. Lighter than Speedgoat. Good choice if you alternate between roads and light trails.",
      },
      {
        version: "8",
        year: 2025,
        spec: { heelStack: 31, forefootStack: 27, drop: 4, weightGrams: 251, msrp: 130 },
        foam: "CMEVA",
        plate: { present: false },
        surfaces: ["trail", "road"],
        rocker: true,
        features: ["+1mm stack", "4g lighter", "updated outsole pattern", "road-trail versatility"],
        useCases: ["trail", "daily-trainer"],
        notes: "Marathon Sports 'Best Technical Trail HOKA 2026'. Lighter Challenger 7 with minor improvements.",
      },
    ],
  },
];
