import type { Shoe } from "../types.js";

export const NEW_BALANCE: Shoe[] = [
  // ── DAILY TRAINERS ─────────────────────────────────────────────────────────

  {
    id: "nb-860",
    brand: "New Balance",
    model: "Fresh Foam X 860",
    category: "stability",
    cushion: "moderate",
    variants: [
      {
        version: "v14",
        year: 2023,
        spec: { heelStack: 39, forefootStack: 33, drop: 6, weightGrams: 307, msrp: 140 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E", "4E"],
        features: ["medial post", "ABZORB SBS crash pad", "engineered mesh upper"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "Workhorse moderate-overpronation stability trainer. Reliable and wide-format friendly.",
      },
      {
        version: "v15",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 329, msrp: 140, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 329, widths: ["D", "2E", "4E"] },
          womens: { weightGrams: 261, widths: ["B", "D", "2E"], refSize: "women's US 8" },
        },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["B", "D", "2E", "4E"],
        features: ["medial post", "stiffer forefoot", "wider platform", "updated bootie construction"],
        useCases: ["daily-trainer", "long-run", "walking"],
        notes: "+1mm stack, +22g vs v14 (men's). Women's is significantly lighter at 261g/9.2oz. Stiffer forefoot limits MTP extension — useful for hallux rigidus or metatarsalgia. Moderate stability, not aggressive correction.",
      },
    ],
  },

  {
    id: "nb-880",
    brand: "New Balance",
    model: "Fresh Foam X 880",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "v14",
        year: 2023,
        spec: { heelStack: 38, forefootStack: 32, drop: 6, weightGrams: 295, msrp: 140 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E", "4E"],
        features: ["dual-density Fresh Foam X", "no-sew overlays", "blown rubber outsole"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Neutral daily workhorse. Firm, responsive ride — sits between 860 (stability) and 1080 (plush) in the NB lineup.",
      },
      {
        version: "v15",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 300, msrp: 140, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 300, widths: ["D", "2E", "4E"] },
          womens: { weightGrams: 255, widths: ["B", "D", "2E"], refSize: "women's US 8" },
        },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E", "4E"],
        features: ["firmer midsole than 1080 v14", "stiffer forefoot toe box", "quick heel-to-toe transition"],
        useCases: ["daily-trainer", "long-run", "tempo"],
        notes: "Firmer and more energetic than the 1080 despite sharing the Fresh Foam X label. Men's 300g vs women's 255g. Excellent workhorse for runners who find the 1080 too soft.",
      },
    ],
  },

  {
    id: "nb-1080",
    brand: "New Balance",
    model: "Fresh Foam X 1080",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "v13",
        year: 2023,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 303, msrp: 165 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["ultra-plush Fresh Foam X", "hypoknit upper", "blown rubber outsole"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Very soft cloud-like ride. v13 was notably soft — some found it too unstable at pace. v14 corrected this.",
      },
      {
        version: "v14",
        year: 2024,
        spec: { heelStack: 40.5, forefootStack: 34.5, drop: 6, weightGrams: 298, msrp: 165 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["firmer than v13 for stability", "slightly more forefoot flex", "hypoknit upper"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Reined in the excess softness of v13. Firmer, more stable, still plush. Best all-round version before the v15 foam upgrade.",
      },
      {
        version: "v15",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 261, msrp: 170, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 261, widths: ["D", "2E"] },
          womens: { weightGrams: 207, widths: ["B", "D"], refSize: "women's US 8" },
        },
        foam: "Infinion (supercritical)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["Infinion supercritical foam", "37g lighter than v14", "improved energy return", "updated upper"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Biggest upgrade in the 1080 line. Infinion supercritical foam is significantly lighter (261g vs 298g) and more responsive than Fresh Foam X. Released January 2026.",
      },
    ],
  },

  {
    id: "nb-more-v6",
    brand: "New Balance",
    model: "Fresh Foam X More",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "v5",
        year: 2024,
        spec: { heelStack: 36, forefootStack: 32, drop: 4, weightGrams: 312, msrp: 155 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["very high forefoot stack", "4mm low drop", "widened platform"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Low-drop max-cushion. 4mm drop suits those transitioning to lower offset or with Achilles sensitivity. Very wide stable base.",
      },
      {
        version: "v6",
        year: 2025,
        spec: { heelStack: 37, forefootStack: 33, drop: 4, weightGrams: 308, msrp: 160 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        widths: ["D", "2E"],
        features: ["+1mm stack vs More v5", "updated engineered mesh", "4mm low drop maintained"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "Marginal stack increase and upper update over v5. Best pick for runners wanting max cushion with low drop.",
      },
    ],
  },

  {
    id: "nb-kaiha-road",
    brand: "New Balance",
    model: "Fresh Foam X Kaiha Road",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "1",
        year: 2025,
        spec: { heelStack: 35, forefootStack: 27, drop: 8, weightGrams: 280, msrp: 100 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["budget price point", "Fresh Foam X cushioning", "accessible entry to NB run line"],
        useCases: ["daily-trainer", "walking"],
        notes: "Best budget NB runner. Solid everyday shoe without the premium price of 880/1080. Good for beginners or low-mileage runners.",
      },
    ],
  },

  // ── SPEED / TEMPO ───────────────────────────────────────────────────────────

  {
    id: "nb-rebel-v5",
    brand: "New Balance",
    model: "FuelCell Rebel",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "v4",
        year: 2024,
        spec: { heelStack: 35, forefootStack: 27, drop: 8, weightGrams: 226, msrp: 140 },
        foam: "FuelCell (nitrogen-infused)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["highly responsive FuelCell foam", "lightweight", "versatile tempo trainer"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "NB's energetic speed trainer. No plate — pure FuelCell foam propulsion. Great daily driver for faster runners.",
      },
      {
        version: "v5",
        year: 2025,
        spec: { heelStack: 36, forefootStack: 28, drop: 8, weightGrams: 222, msrp: 140 },
        foam: "FuelCell (reformulated, softer)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["softer reformulated FuelCell vs v4", "4g lighter", "+1mm stack"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "Softer FuelCell foam than v4 while retaining responsiveness. Best for daily miles and 5K–10K racing. Runner's World 'Best for Speed Training' 2026.",
      },
    ],
  },

  {
    id: "nb-sc-trainer-v3",
    brand: "New Balance",
    model: "FuelCell SuperComp Trainer",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "v3",
        year: 2024,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 244, msrp: 190 },
        foam: "FuelCell (supercritical)",
        plate: { present: true, material: "carbon", description: "Energy Arc partial carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["Energy Arc carbon plate", "FuelCell supercritical foam", "daily training companion to SC Elite"],
        useCases: ["tempo", "long-run", "daily-trainer"],
        notes: "Carbon-plated training version of the SC Elite. More durable than the race shoe, good for marathon-pace workouts and long runs at target pace.",
      },
    ],
  },

  {
    id: "nb-sc-pacer-v2",
    brand: "New Balance",
    model: "FuelCell SuperComp Pacer",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "v2",
        year: 2025,
        spec: { heelStack: 38, forefootStack: 30, drop: 8, weightGrams: 230, msrp: 175 },
        foam: "FuelCell",
        plate: { present: true, material: "carbon", description: "Energy Arc carbon" },
        surfaces: ["road", "track"],
        rocker: true,
        features: ["Energy Arc carbon plate", "FuelCell foam", "plated racer/trainer hybrid"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "Mid-tier plated option between Rebel (plateless) and SC Elite (race). Good for half-marathon and 10K racing.",
      },
    ],
  },

  // ── RACE ────────────────────────────────────────────────────────────────────

  {
    id: "nb-sc-elite-v5",
    brand: "New Balance",
    model: "FuelCell SuperComp Elite",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "v4",
        year: 2024,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 194, msrp: 250 },
        foam: "FuelCell (supercritical)",
        plate: { present: true, material: "carbon", description: "Energy Arc full-length carbon" },
        surfaces: ["road"],
        rocker: true,
        features: ["Energy Arc carbon plate (wraps midsole perimeter)", "supercritical FuelCell foam", "racing geometry"],
        useCases: ["race", "tempo"],
        notes: "NB's flagship marathon racer. Energy Arc carbon plate wraps the midsole perimeter for unique propulsive feel. Competes with Vaporfly and Adios Pro.",
      },
      {
        version: "v5",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 190, msrp: 275 },
        foam: "FuelCell (supercritical, updated)",
        plate: { present: true, material: "carbon", description: "Energy Arc carbon" },
        surfaces: ["road"],
        rocker: true,
        features: ["updated Energy Arc geometry", "improved upper", "4g lighter than v4"],
        useCases: ["race", "tempo"],
        notes: "Lighter than v4. Runner's World 'Best for Racing' 2026. Strong contender for sub-elite marathon racing.",
      },
    ],
  },

  // ── TRAIL ────────────────────────────────────────────────────────────────────

  {
    id: "nb-hierro-v9",
    brand: "New Balance",
    model: "Fresh Foam X Hierro",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "v8",
        year: 2023,
        spec: { heelStack: 33, forefootStack: 25, drop: 8, weightGrams: 310, msrp: 145 },
        foam: "Fresh Foam X",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: false,
        features: ["Vibram Megagrip outsole", "Fresh Foam X cushioning", "rock plate protection"],
        useCases: ["trail"],
        notes: "NB's trail flagship. Vibram Megagrip outsole provides excellent multi-terrain traction. Protective rock plate.",
      },
      {
        version: "v9",
        year: 2025,
        spec: { heelStack: 33, forefootStack: 25, drop: 8, weightGrams: 306, msrp: 145 },
        foam: "Fresh Foam X (dual-density: soft top, firm bottom)",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: false,
        features: ["dual-density Fresh Foam X", "Vibram Megagrip outsole", "rock plate", "protective toe cap"],
        useCases: ["trail"],
        notes: "Runner's World 'Best Trail Shoe' 2026. Dual-density foam: soft top for cushioning, firmer bottom for sharp debris protection.",
      },
    ],
  },
];
