import type { Shoe } from "../types.js";

export const ON_RUNNING: Shoe[] = [
  {
    id: "on-cloudsurfer",
    brand: "On",
    model: "Cloudsurfer",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "7",
        year: 2024,
        spec: { heelStack: 34, forefootStack: 26, drop: 8, weightGrams: 270, msrp: 160 },
        foam: "CloudTec Phase + Helion Superfoam",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["CloudTec Phase pods", "Helion Superfoam", "8mm drop", "smooth responsive transitions"],
        useCases: ["daily-trainer", "tempo"],
        notes: "On's versatile daily trainer. CloudTec Phase creates progressive cushion underfoot. Helion Superfoam delivers balanced energy return.",
      },
    ],
  },

  {
    id: "on-cloudrunner",
    brand: "On",
    model: "Cloudrunner",
    category: "stability",
    cushion: "moderate",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 33, forefootStack: 25, drop: 8, weightGrams: 280, msrp: 160 },
        foam: "CloudTec + Helion Superfoam",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["mild stability guidance", "CloudTec pods", "8mm drop", "wider base"],
        useCases: ["daily-trainer", "long-run"],
        notes: "On's mild stability option. CloudTec pods provide cushion with slight stability guidance. Good for runners wanting On's feel with mild overpronation support.",
      },
      {
        version: "3",
        year: 2026,
        spec: { heelStack: 34, forefootStack: 26, drop: 8, weightGrams: 276, msrp: 165 },
        foam: "CloudTec + Helion Superfoam",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["+1mm stack", "4g lighter", "updated upper", "RTINGS top pick"],
        useCases: ["daily-trainer", "long-run"],
        notes: "RTINGS listed as popular On shoe 2026. Incremental update to Cloudrunner 2.",
      },
    ],
  },

  {
    id: "on-cloudmonster",
    brand: "On",
    model: "Cloudmonster",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 33, drop: 6, weightGrams: 285, msrp: 170 },
        foam: "CloudTec Phase (large pods) + Helion Superfoam",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["large CloudTec Phase pods (max cushion)", "Helion Superfoam", "6mm drop", "springy character"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "On's max-cushion offering. Large CloudTec Phase pods compress for progressive cushion and return energy. 6mm drop. Springier than HOKA Bondi.",
      },
      {
        version: "3 Hyper",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 34, drop: 6, weightGrams: 280, msrp: 185 },
        foam: "CloudTec Phase + Helion Superfoam (Hyper)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["Hyper foam variant", "+1mm stack", "5g lighter", "more responsive than Cloudmonster 2"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "RTINGS listed in popular shoes 2026. Hyper variant adds more energy return to the Cloudmonster formula.",
      },
    ],
  },

  {
    id: "on-cloudstratus",
    brand: "On",
    model: "Cloudstratus",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "3",
        year: 2024,
        spec: { heelStack: 33, forefootStack: 24, drop: 9, weightGrams: 298, msrp: 170 },
        foam: "Helion Superfoam (dual-layer CloudTec)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["double CloudTec layer", "Helion Superfoam", "9mm drop"],
        useCases: ["daily-trainer", "long-run"],
        notes: "On's most stable/cushioned standard trainer. Dual CloudTec layers for progressive cushioning. 9mm drop.",
      },
    ],
  },

  {
    id: "on-cloudboom-echo",
    brand: "On",
    model: "Cloudboom Echo",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "3",
        year: 2024,
        spec: { heelStack: 38, forefootStack: 30, drop: 8, weightGrams: 237, msrp: 210 },
        foam: "Helion Superfoam",
        plate: { present: true, material: "carbon", description: "Speedboard carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["Speedboard carbon plate", "Helion Superfoam", "8mm drop", "race shoe"],
        useCases: ["race", "tempo"],
        notes: "On's carbon marathon racer. Speedboard carbon plate gives distinctive propulsive feel. 8mm drop. Highly regarded for its balance of cushion and speed.",
      },
    ],
  },
];
