import type { Shoe } from "../types.js";

export const PUMA: Shoe[] = [
  // ── DAILY TRAINERS ───────────────────────────────────────────────────────────

  {
    id: "puma-velocity-nitro",
    brand: "PUMA",
    model: "Velocity NITRO",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "3",
        year: 2024,
        spec: { heelStack: 34, forefootStack: 26, drop: 8, weightGrams: 266, msrp: 130 },
        foam: "NITROFOAM (nitrogen-infused EVA)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["NITROFOAM nitrogen-infused EVA", "8mm drop", "PUMAGRIP outsole"],
        useCases: ["daily-trainer", "long-run"],
        notes: "PUMA's accessible neutral daily trainer. NITROFOAM delivers better energy return than standard EVA at an accessible price.",
      },
      {
        version: "4",
        year: 2025,
        spec: { heelStack: 35, forefootStack: 27, drop: 8, weightGrams: 262, msrp: 130 },
        foam: "NITROFOAM",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+1mm stack", "4g lighter", "improved PUMAGRIP outsole — RunRepeat 'best traction'"],
        useCases: ["daily-trainer", "long-run"],
        notes: "RunRepeat 'Best Traction PUMA 2026'. Incremental improvement on v3. PUMAGRIP outsole excels in wet conditions.",
      },
    ],
  },

  {
    id: "puma-magnify-nitro",
    brand: "PUMA",
    model: "Magnify NITRO",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 38, forefootStack: 29, drop: 9, weightGrams: 278, msrp: 150 },
        foam: "NITROFOAM (expanded)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["expanded NITROFOAM for max cushion", "9mm drop", "PUMAGRIP outsole"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "PUMA's max-cushion daily trainer. Expanded NITROFOAM provides plush ride. Competes with Triumph 22 and Bondi 8.",
      },
      {
        version: "3",
        year: 2025,
        spec: { heelStack: 39, forefootStack: 30, drop: 9, weightGrams: 275, msrp: 150 },
        foam: "NITROFOAM (expanded, updated)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+1mm stack", "3g lighter", "updated upper geometry"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "RunRepeat 'Best Daily Trainer PUMA 2026'. Marginal improvements on Magnify 2. Strong value at $150 for max-cushion performance.",
      },
    ],
  },

  {
    id: "puma-magmax-nitro",
    brand: "PUMA",
    model: "MagMax NITRO",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "2",
        year: 2025,
        spec: { heelStack: 45, forefootStack: 35, drop: 10, weightGrams: 298, msrp: 165 },
        foam: "NITROFOAM (maximum stack)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["45mm heel stack", "rocker geometry", "maximum shock absorption in PUMA line", "10mm drop"],
        useCases: ["daily-trainer", "long-run", "recovery", "walking"],
        notes: "RunRepeat 'Best Shock Absorption PUMA 2026'. PUMA's most cushioned shoe. Very high 45mm stack with rocker for smooth transitions. Good for recovery and walking.",
      },
    ],
  },

  {
    id: "puma-foreverrun-nitro",
    brand: "PUMA",
    model: "ForeverRun NITRO",
    category: "stability",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2025,
        spec: { heelStack: 36, forefootStack: 27, drop: 9, weightGrams: 285, msrp: 140 },
        foam: "NITROFOAM + NITRO stability foam",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["GuideRail-style stability system", "dual-density NITRO foam", "9mm drop"],
        useCases: ["daily-trainer", "long-run"],
        notes: "RunRepeat 'Best Stability PUMA 2026'. PUMA's stability trainer. Dual-density NITRO foam provides medial guidance without aggressive post.",
      },
    ],
  },

  // ── SPEED / PERFORMANCE ──────────────────────────────────────────────────────

  {
    id: "puma-deviate-nitro",
    brand: "PUMA",
    model: "Deviate NITRO",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "3",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 30, drop: 9, weightGrams: 261, msrp: 170 },
        foam: "NITROFOAM + NITRO ELITE top",
        plate: { present: true, material: "carbon-composite", description: "PWRPLATE carbon composite" },
        surfaces: ["road"],
        rocker: true,
        features: ["PWRPLATE carbon composite", "dual NITROFOAM layers", "9mm drop", "smooth ride"],
        useCases: ["tempo", "daily-trainer", "race"],
        notes: "Dual NITRO foam + PWRPLATE carbon composite. Combines smooth comfortable ride with speed assistance. RunRepeat 'Best Overall PUMA 2026'.",
      },
      {
        version: "4",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 31, drop: 9, weightGrams: 258, msrp: 175 },
        foam: "NITROFOAM (enhanced)",
        plate: { present: true, material: "carbon-composite", description: "PWRPLATE carbon composite" },
        surfaces: ["road"],
        rocker: true,
        features: ["enhanced NITROFOAM", "+1mm stack", "3g lighter", "PWRPLATE", "combines smooth Deviate 3 ride with speed of Deviate 2"],
        useCases: ["tempo", "daily-trainer", "race"],
        notes: "Supwell: 'favourite Deviate yet — combines smooth ride of v3 with speed assistance of v2'. Best uptempo daily trainer in PUMA line.",
      },
    ],
  },

  // ── RACE ─────────────────────────────────────────────────────────────────────

  {
    id: "puma-deviate-nitro-elite",
    brand: "PUMA",
    model: "Deviate NITRO Elite",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "3",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 31, drop: 8, weightGrams: 194, msrp: 225 },
        foam: "NITRO ELITE (TPEE-based)",
        plate: { present: true, material: "carbon-composite", description: "PWRPLATE carbon composite" },
        surfaces: ["road"],
        rocker: true,
        features: ["NITRO ELITE TPEE foam", "PWRPLATE carbon", "8mm drop", "versatile racer"],
        useCases: ["race", "tempo"],
        notes: "RunRepeat 'Best Marathon PUMA 2026'. Versatile racer that's more approachable than Fast-R while still very fast. Stable platform.",
      },
      {
        version: "4",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 191, msrp: 250 },
        foam: "ATPU (advanced thermoplastic polyurethane)",
        plate: { present: true, material: "carbon-composite", description: "PWRPLATE carbon composite" },
        surfaces: ["road"],
        rocker: true,
        features: ["ATPU foam (upgrade from NITRO ELITE)", "3g lighter", "+1mm stack", "8mm drop"],
        useCases: ["race", "tempo"],
        notes: "Updated to ATPU foam — Supwell: 'among the fastest shoes on the market'. More approachable than Fast-R 3. Good for sub-elite marathoners.",
      },
    ],
  },

  {
    id: "puma-fast-r-nitro-elite",
    brand: "PUMA",
    model: "Fast-R NITRO Elite",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 31, drop: 8, weightGrams: 188, msrp: 275 },
        foam: "ATPU foam",
        plate: { present: true, material: "carbon-composite", description: "PWRPLATE full-length" },
        surfaces: ["road"],
        rocker: true,
        features: ["ATPU foam", "aggressive PWRPLATE", "aggressive toe-off", "bouncy responsive ride"],
        useCases: ["race"],
        notes: "PUMA's fastest race shoe. Aggressive geometry for all-out PR attempts. Bouncy ATPU foam.",
      },
      {
        version: "3",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 170, msrp: 300 },
        foam: "ATPU foam (updated)",
        plate: { present: true, material: "carbon-composite", description: "PWRPLATE aggressive geometry" },
        surfaces: ["road"],
        rocker: true,
        features: ["lightest PUMA race shoe ever", "18g lighter than Fast-R 2", "ATPU foam", "aggressive PWRPLATE"],
        useCases: ["race"],
        notes: "Supwell '#1 Fastest Puma 2026'. 170g. One of the lightest carbon racers available. Lab-tested to be highly efficient. 8mm drop.",
      },
    ],
  },
];
