import type { Shoe } from "../types.js";

export const SAUCONY: Shoe[] = [
  // ── DAILY NEUTRAL ────────────────────────────────────────────────────────────

  {
    id: "saucony-kinvara",
    brand: "Saucony",
    model: "Kinvara",
    category: "neutral",
    cushion: "low",
    variants: [
      {
        version: "14",
        year: 2023,
        spec: { heelStack: 28, forefootStack: 24, drop: 4, weightGrams: 219, msrp: 110 },
        foam: "PWRRUN",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["4mm low drop", "lightweight", "PWRRUN foam", "flexible forefoot"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "Long-running lightweight trainer. 4mm drop encourages midfoot landing. Light and flexible. Best for experienced runners comfortable with low drop.",
      },
      {
        version: "16",
        year: 2025,
        spec: { heelStack: 30, forefootStack: 26, drop: 4, weightGrams: 216, msrp: 120 },
        foam: "PWRRUN",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["4mm drop", "3g lighter than Kinvara 14", "+2mm stack", "updated upper"],
        useCases: ["daily-trainer", "tempo", "race"],
        notes: "RunRepeat 'Best Lightweight Saucony 2026'. Marginal improvements over v14. Great budget race/speed option with 4mm drop.",
      },
    ],
  },

  {
    id: "saucony-ride",
    brand: "Saucony",
    model: "Ride",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "16",
        year: 2023,
        spec: { heelStack: 33, forefootStack: 25, drop: 8, weightGrams: 284, msrp: 130 },
        foam: "PWRRUN+",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["PWRRUN+ expanded cell foam", "8mm drop", "FORMFIT construction"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Reliable neutral daily trainer. PWRRUN+ is lighter and more responsive than standard EVA. 8mm drop versatile for most runners.",
      },
      {
        version: "17",
        year: 2024,
        spec: { heelStack: 33, forefootStack: 25, drop: 8, weightGrams: 282, msrp: 140 },
        foam: "PWRRUN+",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["updated upper", "slightly wider platform", "FORMFIT"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Incremental update to Ride 16. Marginally lighter. Consistent workhorse neutral trainer. Competes with NB 880 v15 and Brooks Ghost 17.",
      },
      {
        version: "18",
        year: 2025,
        spec: { heelStack: 34, forefootStack: 26, drop: 8, weightGrams: 280, msrp: 140 },
        foam: "PWRRUN+",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+1mm stack vs Ride 17", "improved outsole coverage", "updated engineered mesh"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Best Ride yet. Slightly more cushion with same 8mm drop.",
      },
      {
        version: "19",
        year: 2026,
        spec: { heelStack: 35, forefootStack: 27, drop: 8, weightGrams: 278, msrp: 145 },
        foam: "PWRRUN+",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+1mm stack vs Ride 18", "updated geometry", "improved heel tab"],
        useCases: ["daily-trainer", "long-run"],
        notes: "RunRepeat 'Best Daily Trainer Saucony 2026'. Another marginal stack increment. Strong competitor to Ghost 17 and NB 880.",
      },
    ],
  },

  {
    id: "saucony-triumph",
    brand: "Saucony",
    model: "Triumph",
    category: "neutral",
    cushion: "max",
    variants: [
      {
        version: "21",
        year: 2023,
        spec: { heelStack: 36, forefootStack: 26, drop: 10, weightGrams: 290, msrp: 165 },
        foam: "PWRRUN+ (expanded)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["thicker PWRRUN+ vs Ride", "FORMFIT construction", "10mm drop"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Saucony's max-cushion neutral flagship. Comfort-first for easy days and long runs.",
      },
      {
        version: "22",
        year: 2024,
        spec: { heelStack: 37, forefootStack: 27, drop: 10, weightGrams: 287, msrp: 165 },
        foam: "PWRRUN+ (expanded)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+1mm stack", "updated upper", "slightly lighter"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "Marginally more stack and comfort. Competes with NB 1080 v14 and HOKA Bondi 9.",
      },
      {
        version: "23",
        year: 2025,
        spec: { heelStack: 38, forefootStack: 28, drop: 10, weightGrams: 285, msrp: 165, refSize: "men's US 9" },
        genderVariants: {
          mens:   { weightGrams: 285, refSize: "men's US 9" },
          womens: { weightGrams: 258, refSize: "women's US 8" },  // ~9.1oz
        },
        foam: "PWRRUN+ (expanded)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["plush easy-day character", "updated comfort geometry", "improved upper"],
        useCases: ["daily-trainer", "long-run", "recovery"],
        notes: "RunRepeat 'Best Shock Absorption Saucony 2026'. Top comfort-first daily trainer for easy runs and recovery. Women's: ~9.1oz/258g.",
      },
    ],
  },

  // ── STABILITY ───────────────────────────────────────────────────────────────

  {
    id: "saucony-guide",
    brand: "Saucony",
    model: "Guide",
    category: "stability",
    cushion: "moderate",
    variants: [
      {
        version: "17",
        year: 2024,
        spec: { heelStack: 33, forefootStack: 25, drop: 8, weightGrams: 289, msrp: 140 },
        foam: "PWRRUN",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["medial post (firmer PWRRUN density)", "FORMFIT construction", "8mm drop"],
        useCases: ["daily-trainer", "long-run"],
        notes: "Saucony's stability workhorse. 8mm drop lower than Brooks/ASICS stability competitors (10–12mm). Firm but not rigid medial post. Good for mild-to-moderate overpronators.",
      },
      {
        version: "18",
        year: 2026,
        spec: { heelStack: 34, forefootStack: 26, drop: 8, weightGrams: 286, msrp: 145 },
        foam: "PWRRUN",
        plate: { present: false },
        surfaces: ["road"],
        rocker: false,
        features: ["+1mm stack", "updated medial post geometry", "improved upper lockdown"],
        useCases: ["daily-trainer", "long-run"],
        notes: "RunRepeat 'Best Arch Support Saucony 2026'. Incremental improvement on Guide 17. 8mm drop remains distinguishing feature vs competitors.",
      },
    ],
  },

  // ── SPEED / PERFORMANCE ──────────────────────────────────────────────────────

  {
    id: "saucony-endorphin-speed",
    brand: "Saucony",
    model: "Endorphin Speed",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "4",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 31, drop: 8, weightGrams: 234, msrp: 190 },
        foam: "PWRRUN PB (PEBA blend)",
        plate: { present: true, material: "nylon", description: "SpeedRoll nylon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["SpeedRoll nylon plate", "PWRRUN PB PEBA foam", "SpeedRoll geometry", "lightweight"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "Best non-carbon 'super trainer'. SpeedRoll nylon plate costs much less than carbon while delivering meaningful propulsion. PWRRUN PB is highly responsive.",
      },
      {
        version: "5",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 230, msrp: 195 },
        foam: "PWRRUN PB (updated)",
        plate: { present: true, material: "nylon", description: "SpeedRoll nylon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["+1mm stack", "4g lighter", "updated SpeedRoll geometry", "improved PWRRUN PB"],
        useCases: ["tempo", "race", "daily-trainer"],
        notes: "RunRepeat 'Best Tempo Saucony 2026'. Lighter and slightly more stack. SpeedRoll nylon plate continues to be the defining feature.",
      },
    ],
  },

  {
    id: "saucony-endorphin-pro",
    brand: "Saucony",
    model: "Endorphin Pro",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "4",
        year: 2024,
        spec: { heelStack: 39, forefootStack: 31, drop: 8, weightGrams: 202, msrp: 225 },
        foam: "PWRRUN PB (PEBA)",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["full-length carbon plate", "PWRRUN PB PEBA foam", "race-ready geometry"],
        useCases: ["race", "tempo"],
        notes: "Saucony's flagship carbon marathon racer. PWRRUN PB PEBA + carbon plate delivers elite energy return.",
      },
      {
        version: "5",
        year: 2025,
        spec: { heelStack: 39.5, forefootStack: 31.5, drop: 8, weightGrams: 198, msrp: 225 },
        foam: "PWRRUN PB (PEBA, updated)",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["4g lighter than Pro 4", "updated PWRRUN PB foam", "refined carbon plate geometry"],
        useCases: ["race", "tempo"],
        notes: "RunRepeat 'Best Overall Saucony 2026'. 198g. 39.5/31.5mm stack, 8mm drop. Highly competitive with Vaporfly and Adios Pro. Released March 2025.",
      },
    ],
  },

  {
    id: "saucony-endorphin-elite",
    brand: "Saucony",
    model: "Endorphin Elite",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "2",
        year: 2025,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 189, msrp: 280 },
        foam: "PWRRUN HG (highest grade PEBA)",
        plate: { present: true, material: "carbon", description: "full-length carbon plate" },
        surfaces: ["road"],
        rocker: true,
        features: ["PWRRUN HG ultra-premium PEBA", "full carbon plate", "race-optimized geometry", "lightest in Saucony lineup"],
        useCases: ["race", "tempo"],
        notes: "RunRepeat 'Best Energy Return Saucony 2026'. Ultra-premium PWRRUN HG PEBA foam. The Elite 2 provides a ride 'unlike anything else' per Meta Endurance. Faster than Pro 5 for most runners.",
      },
    ],
  },

  {
    id: "saucony-endorphin-azura",
    brand: "Saucony",
    model: "Endorphin Azura",
    category: "neutral",
    cushion: "high",
    variants: [
      {
        version: "1",
        year: 2026,
        spec: { heelStack: 40, forefootStack: 32, drop: 8, weightGrams: 212, msrp: 195 },
        foam: "PWRRUN PB (PEBA)",
        plate: { present: false },
        surfaces: ["road"],
        rocker: true,
        features: ["plateless PWRRUN PB super trainer", "40mm unplated PEBA", "8mm drop", "SpeedRoll-inspired geometry"],
        useCases: ["daily-trainer", "tempo", "long-run"],
        notes: "New 2026 shoe. RTINGS top-ranked shoe. Plateless PWRRUN PB super trainer — positioned as direct competitor to adidas EVO SL. 'Fast and light with a focus on the joy of running.'",
      },
    ],
  },

  // ── TRAIL ────────────────────────────────────────────────────────────────────

  {
    id: "saucony-peregrine",
    brand: "Saucony",
    model: "Peregrine",
    category: "neutral",
    cushion: "moderate",
    variants: [
      {
        version: "14",
        year: 2024,
        spec: { heelStack: 28, forefootStack: 22, drop: 4, weightGrams: 272, msrp: 140 },
        foam: "PWRRUN",
        plate: { present: false },
        surfaces: ["trail"],
        rocker: false,
        features: ["PWRRUN foam", "4mm drop", "aggressive lug pattern", "stone guard protection"],
        useCases: ["trail"],
        notes: "Saucony's trail flagship. 4mm low drop. Aggressive lugs for muddy/technical terrain. Stone guard underfoot protection.",
      },
    ],
  },
];
