import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { mkdir, rename, stat } from "node:fs/promises";
import path from "node:path";
import { normalizeAbs, requireApproved, riskyFilesystemTarget, runCommand, textResult } from "./shared/linux-safety";

const guidelines = ["Use plan_delete before safe_delete.", "Deletes quarantine to ~/.local/share/keylime/trash instead of permanent removal.", "Broad system paths are refused."];

export default function (pi: ExtensionAPI) {
  pi.registerTool({ name: "inspect_path", label: "Inspect Path", description: "Inspect one filesystem path metadata.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String() }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); const s = await stat(p); return textResult(`${p}\n${s.isDirectory() ? "directory" : s.isFile() ? "file" : "other"}\nsize=${s.size}\nmode=${(s.mode & 0o777).toString(8)}\nmtime=${s.mtime.toISOString()}`, { path: p }); }});
  pi.registerTool({ name: "disk_usage_summary", label: "Disk Usage Summary", description: "Inspect filesystem and directory disk usage.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.Optional(Type.String()) }), async execute(_id: string, params: any) { const args = params.path ? ["-sh", params.path] : ["-h"]; const cmd = params.path ? "du" : "df"; const r = await runCommand({ command: cmd, args }); return textResult(r.stdout || r.stderr); }});
  pi.registerTool({ name: "find_large_files", label: "Find Large Files", description: "Find large files under one path with result caps.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), min_size: Type.Optional(Type.String()), max_results: Type.Optional(Type.Number({ minimum: 1, maximum: 200 })) }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); if (riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const r = await runCommand({ command: "find", args: [p, "-type", "f", "-size", params.min_size ?? "+100M", "-printf", "%s %p\n"] }); return textResult(r.stdout.split("\n").filter(Boolean).sort((a, b) => Number(b.split(" ")[0]) - Number(a.split(" ")[0])).slice(0, params.max_results ?? 50).join("\n") || "No matches"); }});
  pi.registerTool({ name: "find_recent_files", label: "Find Recent Files", description: "Find recently modified files under one path.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), days: Type.Optional(Type.Number({ minimum: 1, maximum: 365 })), max_results: Type.Optional(Type.Number({ minimum: 1, maximum: 200 })) }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); if (riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const r = await runCommand({ command: "find", args: [p, "-type", "f", "-mtime", `-${params.days ?? 7}`, "-printf", "%TY-%Tm-%Td %TH:%TM %p\n"] }); return textResult(r.stdout.split("\n").filter(Boolean).slice(0, params.max_results ?? 50).join("\n") || "No matches"); }});
  pi.registerTool({ name: "plan_delete", label: "Plan Delete", description: "Plan a safe delete/quarantine operation.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String() }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); const reason = riskyFilesystemTarget(p); if (reason) throw new Error(reason); const s = await stat(p); return textResult(`Plan: move ${p} (${s.isDirectory() ? "directory" : "file"}, ${s.size} bytes) to Keylime trash`, { path: p, size: s.size }); }});
  pi.registerTool({ name: "safe_delete", label: "Safe Delete", description: "Quarantine a path after plan_delete review.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String() }), async execute(_id: string, params: any, _signal: any, _onUpdate: any, ctx: any) { const p = normalizeAbs(params.path); const reason = riskyFilesystemTarget(p); if (reason) throw new Error(reason); await requireApproved(ctx, "Safe delete", `Move ${p} to Keylime trash?`); const dir = path.join(process.env.HOME ?? ".", ".local/share/keylime/trash"); await mkdir(dir, { recursive: true }); const dest = path.join(dir, `${path.basename(p)}-${Date.now()}`); await rename(p, dest); return textResult(`Moved ${p} -> ${dest}`, { path: p, trash: dest }); }});
  pi.registerTool({ name: "archive_path", label: "Archive Path", description: "Create a tar.gz archive for one non-critical path.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), output: Type.String() }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); const out = normalizeAbs(params.output); if (riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const r = await runCommand({ command: "tar", args: ["-czf", out, "-C", path.dirname(p), path.basename(p)] }, { timeoutMs: 120_000 }); return textResult(r.stdout || r.stderr || `Created ${out}`, { path: p, output: out }); }});
}
