import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { registerLinuxTool, runCommand, textResult, validateHttpUrl, validateOperand } from "./shared/linux-safety";

const guidelines = ["Use local diagnostics by default.", "Do not scan arbitrary networks; probes are bounded and explicit."];

export default function (pi: ExtensionAPI) {
  registerLinuxTool(pi, { name: "inspect_ports", label: "Inspect Ports", description: "Inspect local listening TCP/UDP services.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { const r = await runCommand({ command: "ss", args: ["-tulpen"] }); return textResult(r.stdout || r.stderr); }});
  registerLinuxTool(pi, { name: "inspect_listening_services", label: "Inspect Listening Services", description: "Alias for local listening service inspection.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { const r = await runCommand({ command: "ss", args: ["-tulpn"] }); return textResult(r.stdout || r.stderr); }});
  registerLinuxTool(pi, { name: "dns_lookup", label: "DNS Lookup", description: "Resolve one hostname with getent.", promptGuidelines: guidelines, parameters: Type.Object({ host: Type.String() }), async execute(_id: string, params: any) { const host = validateOperand(params.host, "host"); const r = await runCommand({ command: "getent", args: ["hosts", host] }); return textResult(r.stdout || r.stderr, { host: params.host }); }});
  registerLinuxTool(pi, { name: "http_probe", label: "HTTP Probe", description: "Bounded HTTP HEAD probe with curl.", promptGuidelines: guidelines, parameters: Type.Object({ url: Type.String() }), async execute(_id: string, params: any) { const url = validateHttpUrl(params.url); const r = await runCommand({ command: "curl", args: ["-I", "--max-time", "10", "--location", "--", url] }); return textResult(r.stdout || r.stderr, { url: params.url }); }});
  registerLinuxTool(pi, { name: "ping_probe", label: "Ping Probe", description: "Send a small bounded ping probe to one host.", promptGuidelines: guidelines, parameters: Type.Object({ host: Type.String(), count: Type.Optional(Type.Number({ minimum: 1, maximum: 5 })) }), async execute(_id: string, params: any) { const host = validateOperand(params.host, "host"); const r = await runCommand({ command: "ping", args: ["-c", String(params.count ?? 3), "--", host] }); return textResult(r.stdout || r.stderr, { host: params.host }); }});
  registerLinuxTool(pi, { name: "trace_route", label: "Trace Route", description: "Trace a route with bounded hops.", promptGuidelines: guidelines, parameters: Type.Object({ host: Type.String(), max_hops: Type.Optional(Type.Number({ minimum: 1, maximum: 30 })) }), async execute(_id: string, params: any) { const host = validateOperand(params.host, "host"); const r = await runCommand({ command: "traceroute", args: ["-m", String(params.max_hops ?? 20), "--", host] }); return textResult(r.stdout || r.stderr, { host: params.host }); }});
  registerLinuxTool(pi, { name: "inspect_routes", label: "Inspect Routes", description: "Inspect IPv4 and IPv6 routing tables and policy rules.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { const parts: string[] = []; for (const args of [["route", "show"], ["-6", "route", "show"], ["rule", "show"]]) { const r = await runCommand({ command: "ip", args }); parts.push(`$ ip ${args.join(" ")}\n${r.stdout || r.stderr}`); } return textResult(parts.join("\n\n")); }});
  registerLinuxTool(pi, { name: "inspect_resolver", label: "Inspect Resolver", description: "Inspect resolver configuration and systemd-resolved status when available.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { let out = ""; try { const r = await runCommand({ command: "resolvectl", args: ["status"] }); out += r.stdout || r.stderr; } catch {} try { const r = await runCommand({ command: "getent", args: ["ahosts", "localhost"] }); out += `\n\nResolver smoke test:\n${r.stdout || r.stderr}`; } catch {} return textResult(out.trim() || "No resolver tooling responded"); }});
  registerLinuxTool(pi, { name: "firewall_status", label: "Firewall Status", description: "Inspect common local firewall status.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { let out = ""; for (const spec of [{ command: "ufw", args: ["status", "verbose"] }, { command: "firewall-cmd", args: ["--state"] }, { command: "nft", args: ["list", "ruleset"] }]) { try { const r = await runCommand(spec); out += `$ ${spec.command} ${spec.args.join(" ")}\n${r.stdout || r.stderr}\n\n`; } catch {} } return textResult(out.trim() || "No common firewall tool responded"); }});
}
