import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { consumeOperationPlan, createOperationPlan, operationTarget, registerLinuxTool, requireApproved, runCommand, textResult, validateOperand, validateSignal } from "./shared/linux-safety";

const guidelines = ["Inspect process identity before signaling.", "plan_kill_process must precede kill_process.", "Critical PID ranges and PID 1 are refused; graceful signals first."];
const denied = new Set([1]);
function assertPid(pid: number) { if (!Number.isInteger(pid) || pid <= 1 || denied.has(pid)) throw new Error(`Refusing critical PID ${pid}`); }

export default function (pi: ExtensionAPI) {
  registerLinuxTool(pi, { name: "list_processes", label: "List Processes", description: "List processes with bounded ps output.", promptGuidelines: guidelines, parameters: Type.Object({ query: Type.Optional(Type.String()) }), async execute(_id: string, params: any) { const r = await runCommand({ command: "ps", args: ["axo", "pid,ppid,user,stat,comm,args", "--sort=-%cpu"] }); const lines = r.stdout.split("\n"); const filtered = params.query ? lines.filter(l => l.includes(params.query) || l.startsWith("PID")) : lines.slice(0, 80); return textResult(filtered.slice(0, 120).join("\n")); }});
  registerLinuxTool(pi, { name: "inspect_process", label: "Inspect Process", description: "Inspect one process by PID.", promptGuidelines: guidelines, parameters: Type.Object({ pid: Type.Number() }), async execute(_id: string, params: any) { assertPid(params.pid); const r = await runCommand({ command: "ps", args: ["-p", String(params.pid), "-o", "pid,ppid,user,stat,etime,comm,args"] }); return textResult(r.stdout || r.stderr, { pid: params.pid }); }});
  registerLinuxTool(pi, { name: "search_processes", label: "Search Processes", description: "Search local process list.", promptGuidelines: guidelines, parameters: Type.Object({ query: Type.String() }), async execute(_id: string, params: any) { const r = await runCommand({ command: "pgrep", args: ["-a", "--", validateOperand(params.query, "process query")] }); return textResult(r.stdout || r.stderr || "No matches", { query: params.query }); }});
  registerLinuxTool(pi, { name: "plan_kill_process", label: "Plan Kill Process", description: "Plan sending a signal to one process after identity check.", promptGuidelines: guidelines, parameters: Type.Object({ pid: Type.Number(), signal: Type.Optional(Type.String()), expected_command: Type.String({ minLength: 1, maxLength: 500 }) }), async execute(_id: string, params: any) { assertPid(params.pid); const r = await runCommand({ command: "ps", args: ["-p", String(params.pid), "-o", "comm=,args="] }); if (params.expected_command && !r.stdout.includes(params.expected_command)) throw new Error("Process identity did not match expected_command"); const signal = validateSignal(params.signal); const target = operationTarget({ pid: params.pid, signal, expected_command: params.expected_command }); const plan = createOperationPlan("kill-process", target); return textResult(`Plan: kill -${signal} -- ${params.pid}\n${r.stdout}`, { pid: params.pid, signal, plan_token: plan.planToken, expires_at: plan.expiresAt }); }});
  registerLinuxTool(pi, { name: "kill_process", label: "Kill Process", description: "Signal one process after plan_kill_process review and confirmation.", promptGuidelines: guidelines, parameters: Type.Object({ pid: Type.Number(), signal: Type.Optional(Type.String()), expected_command: Type.String({ minLength: 1, maxLength: 500 }), plan_token: Type.String() }), async execute(_id: string, params: any, _signal: any, _onUpdate: any, ctx: any) { assertPid(params.pid); const signal = validateSignal(params.signal); const r = await runCommand({ command: "ps", args: ["-p", String(params.pid), "-o", "comm=,args="] }); if (params.expected_command && !r.stdout.includes(params.expected_command)) throw new Error("Process identity did not match expected_command"); consumeOperationPlan(params.plan_token, "kill-process", operationTarget({ pid: params.pid, signal, expected_command: params.expected_command })); await requireApproved(ctx, "Signal process", `kill -${signal} -- ${params.pid}\n${r.stdout}`); const done = await runCommand({ command: "kill", args: [`-${signal}`, "--", String(params.pid)] }); return textResult(done.stdout || done.stderr || "signal sent", { pid: params.pid }); }});
}
