import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { stat } from "node:fs/promises";
import { normalizeAbs, requireApproved, riskyFilesystemTarget, runCommand, sudoPrefix, textResult } from "./shared/linux-safety";

const guidelines = ["Inspect users/groups/permissions before changing them.", "Recursive chmod/chown on broad paths is refused.", "Permission mutations require review and sudo approval."];

export default function (pi: ExtensionAPI) {
  pi.registerTool({ name: "inspect_user", label: "Inspect User", description: "Inspect passwd entry and id groups for a user.", promptGuidelines: guidelines, parameters: Type.Object({ user: Type.Optional(Type.String()) }), async execute(_id: string, params: any) { const user = params.user ?? process.env.USER ?? ""; const id = await runCommand({ command: "id", args: [user] }); const getent = await runCommand({ command: "getent", args: ["passwd", user] }); return textResult(`${id.stdout}\n${getent.stdout}`, { user }); }});
  pi.registerTool({ name: "inspect_groups", label: "Inspect Groups", description: "Inspect group memberships.", promptGuidelines: guidelines, parameters: Type.Object({ user: Type.Optional(Type.String()) }), async execute(_id: string, params: any) { const args = params.user ? [params.user] : []; const r = await runCommand({ command: "groups", args }); return textResult(r.stdout || r.stderr); }});
  pi.registerTool({ name: "inspect_permissions", label: "Inspect Permissions", description: "Inspect ownership and mode for one path.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String() }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); const s = await stat(p); return textResult(`${p}\nuid=${s.uid} gid=${s.gid} mode=${(s.mode & 0o777).toString(8)} type=${s.isDirectory() ? "directory" : s.isFile() ? "file" : "other"}`, { path: p }); }});
  pi.registerTool({ name: "plan_chmod", label: "Plan chmod", description: "Plan a chmod operation with broad-path guards.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), mode: Type.String(), recursive: Type.Optional(Type.Boolean()) }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); return textResult(`Plan: chmod ${params.recursive ? "-R " : ""}${params.mode} ${p}`, { path: p, mode: params.mode, recursive: !!params.recursive }); }});
  pi.registerTool({ name: "apply_permissions_change", label: "Apply Permissions Change", description: "Apply chmod after plan_chmod review and sudo approval.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), mode: Type.String(), recursive: Type.Optional(Type.Boolean()) }), async execute(_id: string, params: any, _signal: any, _onUpdate: any, ctx: any) { const p = normalizeAbs(params.path); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); await requireApproved(ctx, "Apply chmod", `sudo chmod ${params.recursive ? "-R " : ""}${params.mode} ${p}`); const spec = await sudoPrefix(ctx, { command: "chmod", args: [...(params.recursive ? ["-R"] : []), params.mode, p], sudo: true }); const r = await runCommand(spec); return textResult(r.stdout || r.stderr || "chmod completed", { path: p }); }});
  pi.registerTool({ name: "plan_chown", label: "Plan chown", description: "Plan a chown operation with broad-path guards.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), owner: Type.String(), recursive: Type.Optional(Type.Boolean()) }), async execute(_id: string, params: any) { const p = normalizeAbs(params.path); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); return textResult(`Plan: chown ${params.recursive ? "-R " : ""}${params.owner} ${p}`, { path: p, owner: params.owner }); }});
}
