import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { runCommand, textResult } from "./shared/linux-safety";

const guidelines = ["Use local diagnostics by default.", "Do not scan arbitrary networks; probes are bounded and explicit."];

export default function (pi: ExtensionAPI) {
  pi.registerTool({ name: "inspect_ports", label: "Inspect Ports", description: "Inspect local listening TCP/UDP services.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { const r = await runCommand({ command: "ss", args: ["-tulpen"] }); return textResult(r.stdout || r.stderr); }});
  pi.registerTool({ name: "inspect_listening_services", label: "Inspect Listening Services", description: "Alias for local listening service inspection.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { const r = await runCommand({ command: "ss", args: ["-tulpn"] }); return textResult(r.stdout || r.stderr); }});
  pi.registerTool({ name: "dns_lookup", label: "DNS Lookup", description: "Resolve one hostname with getent.", promptGuidelines: guidelines, parameters: Type.Object({ host: Type.String() }), async execute(_id: string, params: any) { const r = await runCommand({ command: "getent", args: ["hosts", params.host] }); return textResult(r.stdout || r.stderr, { host: params.host }); }});
  pi.registerTool({ name: "http_probe", label: "HTTP Probe", description: "Bounded HTTP HEAD probe with curl.", promptGuidelines: guidelines, parameters: Type.Object({ url: Type.String() }), async execute(_id: string, params: any) { const r = await runCommand({ command: "curl", args: ["-I", "--max-time", "10", "--location", params.url] }); return textResult(r.stdout || r.stderr, { url: params.url }); }});
  pi.registerTool({ name: "ping_probe", label: "Ping Probe", description: "Send a small bounded ping probe to one host.", promptGuidelines: guidelines, parameters: Type.Object({ host: Type.String(), count: Type.Optional(Type.Number({ minimum: 1, maximum: 5 })) }), async execute(_id: string, params: any) { const r = await runCommand({ command: "ping", args: ["-c", String(params.count ?? 3), params.host] }); return textResult(r.stdout || r.stderr, { host: params.host }); }});
  pi.registerTool({ name: "trace_route", label: "Trace Route", description: "Trace a route with bounded hops.", promptGuidelines: guidelines, parameters: Type.Object({ host: Type.String(), max_hops: Type.Optional(Type.Number({ minimum: 1, maximum: 30 })) }), async execute(_id: string, params: any) { const r = await runCommand({ command: "traceroute", args: ["-m", String(params.max_hops ?? 20), params.host] }); return textResult(r.stdout || r.stderr, { host: params.host }); }});
  pi.registerTool({ name: "firewall_status", label: "Firewall Status", description: "Inspect common local firewall status.", promptGuidelines: guidelines, parameters: Type.Object({}), async execute() { let out = ""; for (const spec of [{ command: "ufw", args: ["status", "verbose"] }, { command: "firewall-cmd", args: ["--state"] }, { command: "nft", args: ["list", "ruleset"] }]) { try { const r = await runCommand(spec); out += `$ ${spec.command} ${spec.args.join(" ")}\n${r.stdout || r.stderr}\n\n`; } catch {} } return textResult(out.trim() || "No common firewall tool responded"); }});
}
