import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { realpath, stat } from "node:fs/promises";
import { consumeOperationPlan, createOperationPlan, normalizeAbs, operationTarget, registerLinuxTool, requireApproved, riskyFilesystemTarget, runCommand, sudoPrefix, textResult, validateMode, validateOperand } from "./shared/linux-safety";

const guidelines = ["Inspect users/groups/permissions before changing them.", "Recursive chmod/chown on broad paths is refused.", "Permission mutations require review and sudo approval."];

export default function (pi: ExtensionAPI) {
  registerLinuxTool(pi, { name: "inspect_user", label: "Inspect User", description: "Inspect passwd entry and id groups for a user.", promptGuidelines: guidelines, parameters: Type.Object({ user: Type.Optional(Type.String()) }), async execute(_id: string, params: any) { const user = validateOperand(params.user ?? process.env.USER ?? "", "user"); const id = await runCommand({ command: "id", args: ["--", user] }); const getent = await runCommand({ command: "getent", args: ["passwd", user] }); return textResult(`${id.stdout}\n${getent.stdout}`, { user }); }});
  registerLinuxTool(pi, { name: "inspect_groups", label: "Inspect Groups", description: "Inspect group memberships.", promptGuidelines: guidelines, parameters: Type.Object({ user: Type.Optional(Type.String()) }), async execute(_id: string, params: any) { const args = params.user ? ["--", validateOperand(params.user, "user")] : []; const r = await runCommand({ command: "groups", args }); return textResult(r.stdout || r.stderr); }});
  registerLinuxTool(pi, { name: "inspect_permissions", label: "Inspect Permissions", description: "Inspect ownership and mode for one path.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String() }), async execute(_id: string, params: any) { const p = await realpath(normalizeAbs(params.path)); const s = await stat(p); return textResult(`${p}\nuid=${s.uid} gid=${s.gid} mode=${(s.mode & 0o777).toString(8)} type=${s.isDirectory() ? "directory" : s.isFile() ? "file" : "other"}`, { path: p }); }});
  registerLinuxTool(pi, { name: "plan_chmod", label: "Plan chmod", description: "Plan a chmod operation with broad-path guards.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), mode: Type.String(), recursive: Type.Optional(Type.Boolean()) }), async execute(_id: string, params: any) { const p = await realpath(normalizeAbs(params.path)); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const mode = validateMode(params.mode); const target = operationTarget({ path: p, mode, recursive: !!params.recursive }); const plan = createOperationPlan("chmod", target); return textResult(`Plan: chmod ${params.recursive ? "-R " : ""}${mode} -- ${p}`, { path: p, mode, recursive: !!params.recursive, plan_token: plan.planToken, expires_at: plan.expiresAt }); }});
  registerLinuxTool(pi, { name: "apply_permissions_change", label: "Apply Permissions Change", description: "Apply chmod after plan_chmod review and sudo approval.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), mode: Type.String(), recursive: Type.Optional(Type.Boolean()), plan_token: Type.String() }), async execute(_id: string, params: any, _signal: any, _onUpdate: any, ctx: any) { const p = await realpath(normalizeAbs(params.path)); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const mode = validateMode(params.mode); consumeOperationPlan(params.plan_token, "chmod", operationTarget({ path: p, mode, recursive: !!params.recursive })); await requireApproved(ctx, "Apply chmod", `sudo chmod ${params.recursive ? "-R " : ""}${mode} -- ${p}`); const spec = await sudoPrefix(ctx, { command: "chmod", args: [...(params.recursive ? ["-R"] : []), mode, "--", p], sudo: true }); const r = await runCommand(spec); return textResult(r.stdout || r.stderr || "chmod completed", { path: p }); }});
  registerLinuxTool(pi, { name: "plan_chown", label: "Plan chown", description: "Plan a chown operation with broad-path guards.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), owner: Type.String(), recursive: Type.Optional(Type.Boolean()) }), async execute(_id: string, params: any) { const p = await realpath(normalizeAbs(params.path)); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const owner = validateOperand(params.owner, "owner"); if (!/^[A-Za-z0-9_.-]+(?::[A-Za-z0-9_.-]+)?$/.test(owner)) throw new Error("Invalid owner[:group]"); const plan = createOperationPlan("chown", operationTarget({ path: p, owner, recursive: !!params.recursive })); return textResult(`Plan: chown ${params.recursive ? "-R " : ""}${owner} -- ${p}`, { path: p, owner, recursive: !!params.recursive, plan_token: plan.planToken, expires_at: plan.expiresAt }); }});
  registerLinuxTool(pi, { name: "apply_ownership_change", label: "Apply Ownership Change", description: "Apply chown after a matching plan and sudo approval.", promptGuidelines: guidelines, parameters: Type.Object({ path: Type.String(), owner: Type.String(), recursive: Type.Optional(Type.Boolean()), plan_token: Type.String() }), async execute(_id: string, params: any, _signal: any, _onUpdate: any, ctx: any) { const p = await realpath(normalizeAbs(params.path)); if (params.recursive && riskyFilesystemTarget(p)) throw new Error(riskyFilesystemTarget(p)); const owner = validateOperand(params.owner, "owner"); if (!/^[A-Za-z0-9_.-]+(?::[A-Za-z0-9_.-]+)?$/.test(owner)) throw new Error("Invalid owner[:group]"); consumeOperationPlan(params.plan_token, "chown", operationTarget({ path: p, owner, recursive: !!params.recursive })); await requireApproved(ctx, "Apply chown", `sudo chown ${params.recursive ? "-R " : ""}${owner} -- ${p}`); const spec = await sudoPrefix(ctx, { command: "chown", args: [...(params.recursive ? ["-R"] : []), owner, "--", p], sudo: true }); const r = await runCommand(spec); return textResult(r.stdout || r.stderr || "chown completed", { path: p, owner }); }});
}
